### ISSUE TITLE
Unable to install tt-flash

### ISSUE THREAD

**Issue by eyonland** [tenstorrent/tt-flash#3]
Hitting an error following instructions from [ https://docs.tenstorrent.com/tenstorrent/add-in-boards-and-cooling-kits/e75-e150/software-setup#install-tt-flash]( https://docs.tenstorrent.com/tenstorrent/add-in-boards-and-cooling-kits/e75-e150/software-setup#install-tt-flash)

pip install https://github.com/tenstorrent/tt-flash.git -vvv
Using pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
Defaulting to user installation because normal site-packages is not writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-z0_o36n3
Created temporary directory: /tmp/pip-req-tracker-v4dgboo5
Initialized build tracking at /tmp/pip-req-tracker-v4dgboo5
Created build tracker: /tmp/pip-req-tracker-v4dgboo5
Entered build tracker: /tmp/pip-req-tracker-v4dgboo5
Created temporary directory: /tmp/pip-install-gw8rvolj
Collecting https://github.com/tenstorrent/tt-flash.git
  Created temporary directory: /tmp/pip-req-build-pxzcpdw8
  Created temporary directory: /tmp/pip-unpack-0bqkdyyd
  Looking up "https://github.com/tenstorrent/tt-flash.git" in the cache
  Returning cached permanent redirect response (ignoring date and etag information)
  Looking up "https://github.com/tenstorrent/tt-flash" in the cache
  Current age based on date: 61
  Freshness lifetime from max-age: 0
  Starting new HTTPS connection (1): github.com:443
  https://github.com:443 "GET /tenstorrent/tt-flash HTTP/1.1" 200 None
  Downloading https://github.com/tenstorrent/tt-flash.git
     - 98.3 kB 1.8 MB/s 0:00:00  Updating cache with response from "https://github.com/tenstorrent/tt-flash"
  etag object cached for 1209600 seconds
  Caching due to etag
     \ 184.9 kB 2.9 MB/s 0:00:00
  ERROR: Cannot unpack file /tmp/pip-unpack-0bqkdyyd/tt-flash.git (downloaded from /tmp/pip-req-build-pxzcpdw8, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-pxzcpdw8
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 339, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 75, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 506, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 468, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 215, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 288, in __init__
    super().__init__(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
    self.dist = self._prepare()
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
    dist = self._prepare_distribution()
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 299, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 487, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 532, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 224, in unpack_url
    unpack_file(file.path, location, file.content_type)
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/unpacking.py", line 258, in unpack_file
    raise InstallationError(f"Cannot determine archive format of {location}")
pip._internal.exceptions.InstallationError: Cannot determine archive format of /tmp/pip-req-build-pxzcpdw8
Removed build tracker: '/tmp/pip-req-tracker-v4dgboo5'

**Comment by eyonland** [comment]
python3 --version
Python 3.10.12

pip --version
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

**Comment by TTDRosen** [comment]
It looks like the install instructions on the docs website are incorrect.

Try `pip install git+https://github.com/tenstorrent/tt-flash.git` and let me know if you get better results

**Comment by eyonland** [comment]
Yep that worked beautifully!

**Comment by TTDRosen** [comment]
Great! Thanks for filing the issue 😄 I'll get the docs updated to stop others form hitting this same problem.

**Comment by eyonland** [comment]
It looks like tt-flash did not get setup in the $HOME/.local/bin/tt-flash location though.

Using a newer version on Ubuntu by the way...
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

**Comment by TTDRosen** [comment]
Try running `pip list -v` that'll show you if/where pip installed tt-flash

**Comment by eyonland** [comment]
tt-flash does not show up.

**Comment by eyonland** [comment]
I was able to get tt-flash setup properly after the following steps:

1. Installing cargo with `sudo apt install cargo`.  
2. Used pyenv to target version 3.8.10.  
3. pip install git+https://github.com/tenstorrent/tt-flash.git

**Comment by warthog9** [comment]
Docs fixed
